ALTER TABLE revenue_goals ADD COLUMN IF NOT EXISTS staff_id INTEGER REFERENCES staff(id) ON DELETE CASCADE;
ALTER TABLE revenue_goals ADD COLUMN IF NOT EXISTS goal_type VARCHAR(20) DEFAULT 'monthly';
ALTER TABLE revenue_goals ADD COLUMN IF NOT EXISTS description TEXT;
