CREATE TABLE IF NOT EXISTS loyalty_tiers (
    id SERIAL PRIMARY KEY,
    tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    min_points INTEGER NOT NULL DEFAULT 0,
    earn_multiplier DECIMAL(5,2) NOT NULL DEFAULT 1.00,
    badge_color VARCHAR(50),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE customers
ADD COLUMN IF NOT EXISTS tier_id INTEGER REFERENCES loyalty_tiers(id) ON DELETE SET NULL,
ADD COLUMN IF NOT EXISTS referred_by_customer_id INTEGER REFERENCES customers(id) ON DELETE SET NULL;
